### ISSUE TITLE
Output of the decoder

### ISSUE THREAD

**Issue by jiaqingxie** [johncava/GNF-pytorch#1]
Hi, John.
I think your implementation is really intuitive. I am just concerning about the output. I think it should be the reconstructed Adjacency Matrix instead of the reconstructed node features as specified in the original paper. And there're some bugs in the code, for example, if the iteration changes, data will be changed and it will return error. I will implement this and do pull request some days later when I fix it.

**Comment by johncava** [comment]
Hi Jiaqing,
Thanks for taking your time to improve the code!
